package:
  name: openmoltools-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy
    - numpydoc
    - scipy
    - openmm
    - pytables
    - ambertools
    - rdkit    # rdkit is an optional dependency, may want to comment this out for the release version.
  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - lxml
    - pymbar
    - numpy
    - numpydoc
    - scipy
    - openmm
    - pytables
    - ambertools
    - rdkit    # rdkit is an optional dependency, may want to comment this out for the release version.

test:
  requires:
    - nose
    - openmmtools
  imports:
    - openmoltools
  #commands:
  #  - nosetests openmoltools -v -a '!slow'

about:
  home: https://github.com/choderalab/openmoltools
  license: MIT License
